name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # or 'main' if you're using that

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/mern-crud-backend
            git pull origin master
            npm install
            pm2 restart all || pm2 start server.js --name backend
