name: Deploy Backend to EC2

on:
  push:
    branches:
      - master  # ✅ Use 'main' if your repo's default branch is 'main'

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/mern-crud-backend"

      - name: Install dependencies & Restart backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/mern-crud-backend
            npm install
            pm2 restart mern-backend || pm2 start server.js --name mern-backend
