name: Deploy Backend to EC2

on:
  push:
    branches:
      - master  # or 'master' if that's your branch

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/mern-crud-backend
            git pull origin main
            npm install
            pm2 restart all || pm2 start server.js --name backend
